### ISSUE TITLE
Image preview too dark

### ISSUE THREAD

**Issue by githubisviolatingthegpl** [ptrLx/OneShot#5]
Hi,

When attempting to view images (mostly) full-screen, the program applies a dark gradient that obscures the bottom part of the image. 

Running CalyxOS on Pixel 4a 5G.

Screenshot:
![Screenshot_20230316-235332](https://user-images.githubusercontent.com/121033978/225816096-2cb7eaff-9e58-4024-be42-1ecb990196f7.png)

**Comment by githubisviolatingthegpl** [comment]
Actual inage;:
![OneShot_20230302101517](https://user-images.githubusercontent.com/121033978/225816296-6f6f276c-42c1-46b0-91fa-1fbef96b553d.jpg)

**Comment by ptrLx** [comment]
The gradient is applied to ensure that the date is visible. This makes mostly sense in the small image view. In the full screen version I could remove date, gradient and happiness to provide a better experience.

**Comment by ptrLx** [comment]
This will be included in the next release.

**Comment by githubisviolatingthegpl** [comment]
Thank you! :)
