### ISSUE TITLE
feature request. choose which camera to use to take pictures

### ISSUE THREAD

**Issue by Wjxfi** [ptrLx/OneShot#7]
I wanted this because my camera (default) adds unnecessary information to the photo (such as device id and other), in general, ICC profile

I wanted to use an open camera

**Comment by ptrLx** [comment]
OneShot will use the camera app, that is selected as default in Android. You can change the default camera application in your system settings. It's not really easy to implement such a setting in OneShot.

**Comment by ptrLx** [comment]
Apparently, this setting has been removed since Android 11. In addition, apps that want to open the camera app have to use the pre-installed one.
Source:
https://android.stackexchange.com/questions/228774/how-do-we-set-the-default-camera-app-in-android-11
